import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="dark" lang="en">
      <body
        className={`antialiased text-xl dark:bg-dark dark:text-light bg-light text-dark`}
      >
        {children}
        <footer className="w-full flex flex-row items-center justify-center my-4">
          <span>Made by <a className="hover:text-accent-orange" target="_blank" href="https://github.com/ssaxel03">@ssaxel03</a></span>
        </footer>
      </body>
    </html>
  );
}
